import javax.swing.JOptionPane;
public class Payment extends javax.swing.JFrame {
/**
* Creates new form Payment
*/
public Payment() {
initComponents();
}
public Payment(String para){
initComponents();
jLabel4.setText(para);
}
/**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always *
regenerated by the Form Editor.
*/
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {
jLabel3 = new javax.swing.JLabel();
jFormattedTextField1 = new javax.swing.JFormattedTextField();
jPanel1 = new javax.swing.JPanel();
jTextField1 = new javax.swing.JTextField();
jTextField2 = new javax.swing.JTextField();
jTextField3 = new javax.swing.JTextField();
jTextField4 = new javax.swing.JTextField();
jButton1 = new javax.swing.JButton();
jPasswordField1 = new javax.swing.JPasswordField();
jLabel2 = new javax.swing.JLabel();
jTextField5 = new javax.swing.JTextField();
jTextField6 = new javax.swing.JTextField();
jTextField7 = new javax.swing.JTextField();
jLabel5 = new javax.swing.JLabel();
jLabel4 = new javax.swing.JLabel();
jLabel6 = new javax.swing.JLabel();
jButton2 = new javax.swing.JButton();
jLabel1 = new javax.swing.JLabel();
jLabel7 = new javax.swing.JLabel();
jLabel8 = new javax.swing.JLabel();
jLabel9 = new javax.swing.JLabel();
jLabel10 = new javax.swing.JLabel();
jLabel11 = new javax.swing.JLabel();
jLabel12 = new javax.swing.JLabel();
jLabel13 = new javax.swing.JLabel();
jLabel3.setText("jLabel3");
jFormattedTextField1.setText("jFormattedTextField1");
setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
setPreferredSize(new java.awt.Dimension(892, 513));
setSize(new java.awt.Dimension(892, 513));
jPanel1.setBackground(new java.awt.Color(255, 255, 255));
jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
jTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
jTextField1.setForeground(new java.awt.Color(153, 153, 153));
jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
jTextField1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField1ActionPerformed(evt);
}
});
jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 200, 30));
jTextField2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
jTextField2.setForeground(new java.awt.Color(153, 153, 153));
jTextField2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField2ActionPerformed(evt);
}
});
jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 200, 30));
jTextField3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
jTextField3.setForeground(new java.awt.Color(153, 153, 153));
jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 250, 32));
jTextField4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
jTextField4.setForeground(new java.awt.Color(153, 153, 153));
jTextField4.setText(" MM/YY");
jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 74, -1));
jButton1.setBackground(new java.awt.Color(0, 204, 51));
jButton1.setText("PAY NOW");
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton1ActionPerformed(evt);
}
});
jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 320, 31));
jPasswordField1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
jPasswordField1.setText(" CVV");
jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jPasswordField1ActionPerformed(evt);
}
});
jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 52, -1));
jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
jLabel2.setForeground(new java.awt.Color(51, 51, 51));
jLabel2.setText("CVV:");
jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));
jTextField5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
jTextField5.setForeground(new java.awt.Color(153, 153, 153));
jTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
jTextField5.setText("john@example.com");
jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 200, 30));
jTextField6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
jTextField6.setForeground(new java.awt.Color(153, 153, 153));
jTextField6.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField6ActionPerformed(evt);
}
});
jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 110, 30));
jTextField7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
jTextField7.setForeground(new java.awt.Color(153, 153, 153));
jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 80, 30));
jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
jLabel5.setText(" To Pay :");
jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 135, 61));
jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
jLabel4.setText("$ 0.0");
jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 157, 83));
jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sukith Devadiga\\Desktop\\OOC
Project\\logo3.png.jpg")); // NOI18N
jLabel6.setText("jLabel6");
jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 290, 110));
jButton2.setBackground(new java.awt.Color(102, 204, 255));
jButton2.setText("Back");
jButton2.setToolTipText("");
jButton2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton2ActionPerformed(evt);
}
});
jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, 20));
jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sukith Devadiga\\Desktop\\OOC
Project\\logo4.jpg")); // NOI18N
jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 0, 320, 550));
jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
jLabel7.setForeground(new java.awt.Color(51, 51, 51));
jLabel7.setText("NAME :");
jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));
jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
jLabel8.setForeground(new java.awt.Color(51, 51, 51));
jLabel8.setText("ADDRESS :");
jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));
jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
jLabel9.setForeground(new java.awt.Color(51, 51, 51));
jLabel9.setText("Ph. No. :");
jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));
jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
jLabel10.setForeground(new java.awt.Color(51, 51, 51));
jLabel10.setText("Zip Code :");
jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));
jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
jLabel11.setForeground(new java.awt.Color(51, 51, 51));
jLabel11.setText("Card No. :");
jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));
jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
jLabel12.setForeground(new java.awt.Color(51, 51, 51));
jLabel12.setText("Expiry :");
jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));
jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
jLabel13.setForeground(new java.awt.Color(51, 51, 51));
jLabel13.setText("Mail :");
jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));
javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE) );
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE) );
pack();
setLocationRelativeTo(null);
}// </editor-fold>
private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}
private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}
private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
if(jTextField1.getText().equals("") || jTextField2.getText().equals("") || jTextField3.getText().equals("") ||
jTextField4.getText().equals("") || jTextField5.getText().equals("") || jTextField6.getText().equals("") ||
jTextField7.getText().equals("")){
JOptionPane.showMessageDialog(null, "Complete all fields !!","Alert", JOptionPane.CLOSED_OPTION); }
else{
JOptionPane.showMessageDialog(null, "Order placed Successfully..!! ");
this.setVisible(false);
new Final().setVisible(true);
}
// TODO add your handling code here:
}
private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
this.setVisible(false);
new Login().setVisible(true); // TODO add your handling code here: }
private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}
/**
* @param args the command line arguments
*/
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) "> /* If
Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. * For
details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html */
try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) { if
("Nimbus".equals(info.getName())) {
javax.swing.UIManager.setLookAndFeel(info.getClassName());
break;
}
}
} catch (ClassNotFoundException ex) {
java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); } catch
(InstantiationException ex) {
java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); } catch
(IllegalAccessException ex) {
java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); } catch
(javax.swing.UnsupportedLookAndFeelException ex) {
java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); }
//</editor-fold>
/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
new Payment().setVisible(true);
}
});
}
// Variables declaration - do not modify
private javax.swing.JButton jButton1;
private javax.swing.JButton jButton2;
private javax.swing.JFormattedTextField jFormattedTextField1;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel10;
private javax.swing.JLabel jLabel11;
private javax.swing.JLabel jLabel12;
private javax.swing.JLabel jLabel13;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
public javax.swing.JLabel jLabel4;
private javax.swing.JLabel jLabel5;
private javax.swing.JLabel jLabel6;
private javax.swing.JLabel jLabel7;
private javax.swing.JLabel jLabel8;
private javax.swing.JLabel jLabel9;
private javax.swing.JPanel jPanel1;
private javax.swing.JPasswordField jPasswordField1;
private javax.swing.JTextField jTextField1;
private javax.swing.JTextField jTextField2;
private javax.swing.JTextField jTextField3;
private javax.swing.JTextField jTextField4;
private javax.swing.JTextField jTextField5;
private javax.swing.JTextField jTextField6;
private javax.swing.JTextField jTextField7;
// End of variables declaration
}
